name: widget_marquee
description: A marquee for animating looping through widgets horizontally
version: 0.0.7
homepage: https://github.com/StonePack/widget_marquee

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0